labs/lab3/mysiteS20/myapp/urls.py
from django.urls import path
from myapp import views
from django.conf.urls import url


app_name = 'myapp'
urlpatterns = [
    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:top_no>/', views.detail, name='detail'),
    path(r'courses/', views.courses, name='courses'),
    path(r'courses/<int:cour_id>/', views.course_detail, name='course_detail'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'login/', views.user_login, name='user_login'),
    path(r'logout/', views.user_logout, name='user_logout'),
    path(r'myaccount/', views.myaccount, name='myaccount'),
    path(r'register/', views.register, name="register"),
]

labs/lab3/mysiteS20/mysiteS20/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='myapp/password-reset/password_reset_form.html',
             subject_template_name='myapp/password-reset/password_reset_subject.txt',
             email_template_name='myapp/password-reset/password_reset_email.html',
             # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='myapp/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='myapp/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='myapp/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

labs/lab3/mysiteS20/myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from functools import reduce


# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200, blank=False, default='Development')

    def __str__(self):
        return self.name


class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    hours = models.PositiveIntegerField(default=0)
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)

    def __str__(self):
        return self.name

    # If price is greater than 150.00 => discount 10%
    def discount(self):
        self.price = self.price - self.price*10/100  # discount 10%
        self.save()


class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'), ('CG', 'Calgery'), ('MR', 'Montreal'), ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)  # first and last name from User


class Order(models.Model):
    STATUS_CHOICES = [(0, 'Cancelled'), (1, 'Order Confirmed')]
    # course = models.ForeignKey(Course, related_name='courses', on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)
    Student = models.ForeignKey(Student, related_name='student', on_delete=models.CASCADE)
    levels = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    order_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return '{} {} {} {} {} {} {}'.format(self.Student.first_name, self.Student.last_name,
                                             self.levels, self.order_status, self.order_date,
                                             self.total_cost(), self.combined_course_names())

    def combined_course_names(self):
        course_names = ''
        for course in self.courses.all():
            course_names += ' - ' + course.name

        return course_names

    def total_cost(self):
        total_cost = 0
        for course in self.courses.all():
            total_cost += course.price

        return total_cost

labs/lab3/mysiteS20/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from myapp.models import Order, Student
from django.core.validators import MinValueValidator


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['Student', 'courses', 'levels', 'order_date']
        widgets = {
            'student': forms.RadioSelect,
            'order_date': forms.SelectDateWidget,
        }


class InterestForm(forms.Form):
    CHOICES = [('1', 'Yes'), ('0', 'No')]
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    levels = forms.IntegerField(initial=1, validators=[MinValueValidator(1)])
    comments = forms.CharField(label="Additional Comments", widget=forms.Textarea, required=False)


# Register form
class RegisterForm(UserCreationForm):
    class Meta:
        model = Student
        fields = ('username', 'first_name', 'last_name', 'city', 'interested_in')

labs/lab3/mysiteS20/myapp/views.py
# Import necessary classes
from django.conf.urls import url
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from mysiteS20 import settings
from .forms import OrderForm, InterestForm, RegisterForm
from .models import Topic, Course, Student, Order
import datetime


# Create your views here.
@login_required
def index(request):
    if request.session.test_cookie_worked():
        print('Test Cookie Worked. Delete it')
        request.session.delete_test_cookie

    top_list = Topic.objects.all().order_by('id')[:10]
    # get current user in request object
    current_user = request.user

    return render(request, 'myapp/index.html', {'top_list': top_list, 'user': current_user})


def about(request):
    about_visits = request.COOKIES.get('about_visits', 'default')
    if about_visits == 'default':
        response = render(request, 'myapp/about.html', {'about_visits': '1'})
        response.set_cookie('about_visits', 1, 5 * 60)
        # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
        return response
    else:
        about_visits = int(about_visits) + 1
        response = render(request, 'myapp/about.html', {'about_visits': about_visits})
        response.set_cookie('about_visits', about_visits)
        return response


@login_required
def detail(request, top_no):
    topic = get_object_or_404(Topic, pk=top_no)
    course_list = Course.objects.all().filter(topic=top_no)

    return render(request, 'myapp/detail.html', {'topic': topic, 'course_list': course_list})


@login_required
def courses(request):
    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist})


@login_required
def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=True)
            if order.levels <= order.courses.first().stages:
                order.save()
                msg = 'Your course has been ordered successfully.'
                # Update course price if it is greater than 150.00
                if order.courses.first().price > 150.00:
                    order.courses.first().discount()
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/place_order.html', {'form': form, 'msg': msg, 'courlist': courlist})


@login_required
def course_detail(request, cour_id):
    course = get_object_or_404(Course, pk=cour_id)

    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            interest = form.cleaned_data['interested']
            if interest == '1':
                course.interested += 1
                course.save()
            return index(request)
    else:
        form = InterestForm()

    return render(request, 'myapp/course_detail.html', {'form': form, 'course': course})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                current_login_time = str(datetime.datetime.now())
                # session parameter last_login
                request.session['last_login'] = current_login_time
                request.session['username'] = username
                # set session expiry to 1 hour
                # request.session.set_expiry(3600)

                # set session expiry to 0 to expire session at browser close
                request.session.set_expiry(0)

                login(request, user)
                return HttpResponseRedirect(reverse('myapp:myaccount'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return render(request, 'myapp/login.html')
    else:
        # set a test cookie
        print('Set a test cookie')
        request.session.set_test_cookie()
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    try:
        del request.session['last_login']
        del request.session['username']
        request.session.flush()
    except KeyError:
        pass

    return HttpResponseRedirect(reverse('myapp:user_login'))


@login_required
def myaccount(request):
    student = Student.objects.filter(username=request.user.username)
    if len(student) == 1:
        topics = Student.objects.filter(username=request.user.username).first().interested_in.all()
        ordered_courses = Order.objects.filter(Student__username=request.user.username, order_status=1).values_list(
            'courses__id', 'courses__name')

        return render(request, 'myapp/myaccount.html',
                      {'student': student.first(), 'courses': ordered_courses, 'isStudent': 1, 'topics': topics})
    else:
        return render(request, 'myapp/myaccount.html', {'isStudent': 0})


# Register custom view
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)
            student.save()  # save student
            form.save_m2m()  # save topics
            return redirect('myapp:user_login')

    else:
        form = RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})

labs/lab3/mysiteS20/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}About{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    <p>
        <h3>This is an E-learning Website! Search our Topics to find all available Courses.</h3>
    </p>
    </p><b style="text-decoration-color: #d6d8d9">Page Visits:{{ about_visits }}</b></p>
{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html>
   <head lang="en">
        <meta charset="UTF-8">
        <title>About</title>
   </head>
   <body>
        <p>
            <h3>This is an E-learning Website! Search our Topics to find all available Courses.</h3>
        </p>
        <p><a href="/myapp">Main page (hardcoded url)</a></p>
        <p><a href="{% url 'myapp:index' %}">Main page (url namespacing)</a></p>
   </body>
</html>

labs/lab3/mysiteS20/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
        <title>E-Learning WebApp - {% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <div>
            <h1>{% block myhdg %}Hello {{ request.user.first_name }} {{ request.user.last_name }} {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if request.user.is_authenticated %}
                    <li class="hbar1"><a href="/myapp/about/">Find out about our E-Learning site</a></li>
                    <li class="hbar1"><a href="/myapp/courses/">Find out about Courses</a></li>
                    <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
                    <li class="hbar1"><a href="{% url 'myapp:user_logout' %}">Logout</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:myaccount' %}">My Account</a></li>
                {% else %}
                    <li class="hbar1"><a href="{% url 'myapp:user_login' %}">Login</a></li>
                    <li class="hbar1"><a href="{% url 'myapp:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </body>
</html>

labs/lab3/mysiteS20/myapp/templates/myapp/course_detail.html
{% extends 'myapp/base.html' %}
{% block title %}Course Detail{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    {% if course %}
        <h2>Course</h2>
            <p>Name: {{ course.name }}</p>
            <p>Interested: {{ course.interested }}</p>
            <p>Price: {{ course.price }}</p>
            {% if course.for_everyone == False %}
                <p>This course is not for everyone</p>
            {% endif %}
    {% else %}
        <strong>There are no available course!</strong>
    {% endif %}

    <form method="post">
        {%csrf_token%}
        {{form}}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}
{% block title %}Courses{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    {% if courlist %}
          <h2>List of Courses</h2>
        <ol>
            {% for course in courlist %}
                <li> <a href="{% url 'myapp:course_detail' course.id %}">{{ course.name}}</a> </li>
            {% endfor %}
        </ol>
        <a href="{%  url 'myapp:place_order' %}">Place Order</a>
      {% else %}
          <strong>There are no available courses!</strong>
      {% endif %}
{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}Detail{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    {% if topic %}
        <h2>Topic</h2>
            <p>Name: {{ topic.name }}</p>
            <p>Category: {{ topic.category }}</p>
    {% else %}
        <strong>There are no available topic!</strong>
    {% endif %}

    {% if course_list %}
        <h2>List of Courses</h2>
        <ol>
            {% for course in course_list %}
                <li> {{ course.name}} </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}

{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html>
   <head lang="en">
      <meta charset="UTF-8">
      <title>Detail</title>
   </head>
   <body>
      {% if topic %}
          <h2>Topic</h2>
            <p>Name: {{ topic.name }}</p>
           <p>Category: {{ topic.category }}</p>
      {% else %}
          <strong>There are no available topic!</strong>
      {% endif %}
      {% if course_list %}
          <h2>List of Courses</h2>
        <ol>
            {% for course in course_list %}
                <li> {{ course.name}} </li>
            {% endfor %}
        </ol>

      {% else %}
          <strong>There are no available courses!</strong>
      {% endif %}
      <p><a href="{% url 'myapp:index' %}">Main page</a></p>
   </body>
</html>

labs/lab3/mysiteS20/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if top_list %}
          <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li> <a href="{% url 'myapp:detail' top.id %}">{{ top.name}}</a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}

    <br/>
    {% if request.session.last_login%}
        Last Login {{request.session.last_login}}
    {% else %}
        <h2>
            Your login was more than one hour ago
        </h2>
    {% endif %}

{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
   <head lang="en">
      <meta charset="UTF-8">
      <title>E-Learning WebApp!</title>
   </head>
   <body>
      {% if top_list %}
          <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li> <a href="{% url 'myapp:detail' top.id %}">{{ top.name}}</a> </li>
            {% endfor %}
        </ol>
      {% else %}
          <strong>There are no available topics!</strong>
      {% endif %}
      <p><a href="{% url 'myapp:about' %}">About page</a></p>
   </body>
</html>

labs/lab3/mysiteS20/myapp/templates/myapp/login.html
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Login</title>
    </head>
    <body>
        <div style="text-align: center">
            <form method="post" >
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" name="username" value="" id="username"><br>
                <label for="password">Password:</label>
                <input type="password" name="password" value="" id="password"><br>
                <input type="submit" value="Login" />

                <br><br>
                    <a href="{% url 'password_reset' %}">Forgot Password</a>
                <br><br>

            </form>

        </div>
   </body>
</html>

labs/lab3/mysiteS20/myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}
{% block title %}My Account{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    {% if isStudent %}
        <div>
            <ul>
                <li>First Name: {{ student.first_name }}</li>
                <li>Last Name: {{ student.last_name }}</li>
            </ul>
        </div>
        <h2>List of Interested Topics</h2>
        <ol>
            {% for topic in topics %}
                <li>{{ topic.name}}</li>
            {% endfor %}
        </ol>

        <h2>List of Ordered Courses</h2>
        <ol>
            {# Courses is a list of tuples #}
            {% for course in courses %}
                {# Course name #}
                <li>{{ course.1 }}</li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>You are not a registered students</strong>
    {% endif %}
{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block title %}Order Response{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    <p>
        <h3>{{ msg }}.</h3>
    </p>
{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}
{% block title %}Place Order{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    {% if courlist %}
        <h2>List of Courses</h2>
        <ol>
            {% for course in courlist %}
                <li> <a href="">{{ course.name}}</a> </li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available courses!</strong>
    {% endif %}

    <form method="post">
        {%csrf_token%}
        {{form}}
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

labs/lab3/mysiteS20/myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block title %}Register{% endblock %}
{% block myhdg %}{% endblock %}
{% block body_block %}
    <form method="post">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Sign Up" />
    </form>
{% endblock %}